version: '3'

networks:
  backend-demo-r1-net:
    driver: bridge
    name: backend-demo-r1-net

services:
  backend-r1-postgres-12:
    container_name: backend-r1-postgres-12
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB1_PASSWORD}
      POSTGRES_USER: ${DB1_USERNAME}
      POSTGRES_DB: ${DB1_NAME}
    networks:
      - backend-demo-r1-net

  backend-r1-app:
    container_name: backend-r1-app
    image: docker.haulmont.com/platform/infrastructure/demo-cuba-apps-docker/demo-r1/backend-demo-r1:testing
    restart: unless-stopped
    environment:
      RDS_HOSTNAME: backend-r1-postgres-12
      RDS_PASSWORD: ${DB1_PASSWORD}
      RDS_USERNAME: ${DB1_USERNAME}
      RDS_DB_NAME: ${DB1_NAME}
      RDS_PORT: 5432
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8081:8080
    networks:
      - backend-demo-r1-net
      